"""create messages table

Revision ID: 088e5a05770b
Revises: 885c273da8ac
Create Date: 2026-08-03 18:10:39.993726

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '088e5a05770b'
down_revision: Union[str, Sequence[str], None] = '885c273da8ac'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('messages',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('sender_id', sa.UUID(), nullable=False),
    sa.Column('recipient_id', sa.UUID(), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['recipient_id'], ['users.id'], name=op.f('fk_messages_recipient_id_users'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sender_id'], ['users.id'], name=op.f('fk_messages_sender_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_messages'))
    )
    op.create_index('ix_messages_recipient_sender_created', 'messages', ['recipient_id', 'sender_id', 'created_at'], unique=False)
    op.create_index('ix_messages_sender_recipient_created', 'messages', ['sender_id', 'recipient_id', 'created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_messages_sender_recipient_created', table_name='messages')
    op.drop_index('ix_messages_recipient_sender_created', table_name='messages')
    op.drop_table('messages')
    # ### end Alembic commands ###
